name: github-stats
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate stats images
        uses: jstrieb/github-stats@master
        with:
          username: Anthic
          exclude_repos:
          exclude_langs:
          github_token: ${{ secrets.GITHUB_TOKEN }}
